# Generated by Django 4.1.7 on 2023-04-06 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='num_announcements',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
