# Generated by Django 4.1.7 on 2023-03-31 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainer',
            name='date_premium',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainer',
            name='is_premium',
            field=models.BooleanField(default=False),
        ),
    ]
