# Generated by Django 4.1.7 on 2023-03-16 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_client_active_trainer_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='active',
        ),
        migrations.RemoveField(
            model_name='trainer',
            name='active',
        ),
    ]
