# Generated by Django 4.1.7 on 2023-03-17 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_client_picture_alter_trainer_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='birthday',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='birthday',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
