# Generated by Django 4.1.7 on 2023-04-09 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_num_announcements'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avg_rating',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]