# Generated by Django 4.1.7 on 2023-03-19 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_comment'),
        ('users', '0004_alter_client_birthday_alter_trainer_birthday'),
    ]

    operations = [
    ]
