# Generated by Django 4.1.7 on 2023-04-29 11:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Categoria')),
                ('types', models.CharField(choices=[('difficulty', 'Difficulty'), ('objectives', 'Objectives'), ('recovery', 'Recovery'), ('age', 'Age')], default='difficulty', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Calendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('google_calendar_id', models.CharField(max_length=250)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Titulo')),
                ('description', models.TextField(verbose_name='Descripcion')),
                ('place', models.CharField(max_length=250, verbose_name='Lugar')),
                ('price', models.FloatField()),
                ('capacity', models.IntegerField()),
                ('start_date', models.DateTimeField(verbose_name='Fecha de inicio')),
                ('finish_date', models.DateTimeField(verbose_name='Fecha de fin')),
                ('date_created', models.DateField(auto_now_add=True)),
                ('invitation_sent', models.BooleanField(default=False)),
                ('google_calendar_event_id', models.CharField(blank=True, max_length=120, null=True)),
                ('categories', models.ManyToManyField(blank=True, to='announcements.category')),
                ('clients', models.ManyToManyField(blank=True, related_name='announcement_client', to=settings.AUTH_USER_MODEL)),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcement_trainer', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Announcement',
                'verbose_name_plural': 'Announcements',
            },
        ),
    ]
