# Generated by Django 4.1.7 on 2023-03-03 10:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('announcements', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Titulo')),
                ('description', models.TextField(verbose_name='Descripcion')),
                ('place', models.CharField(max_length=250, verbose_name='Lugar')),
                ('price', models.FloatField()),
                ('capacity', models.IntegerField()),
                ('start_date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de inicio')),
                ('finish_date', models.DateTimeField(auto_now=True, verbose_name='Fecha de fin')),
            ],
            options={
                'verbose_name': 'Announcement',
                'verbose_name_plural': 'Announcements',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('LW', 'Lose weight'), ('MM', 'Muscle mass'), ('CF', 'Crossfit'), ('PL', 'Pilates'), ('BX', 'Boxing'), ('AB', 'Aerobic'), ('MA', 'Martial arts')], default='LW', max_length=250, verbose_name='Categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='')),
                ('date_created', models.DateField(auto_now_add=True)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('bio', models.TextField(blank=True, max_length=150, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='')),
                ('date_created', models.DateField(auto_now_add=True)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('bio', models.TextField(blank=True, max_length=150, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Announcements',
        ),
        migrations.AddField(
            model_name='announcement',
            name='categories',
            field=models.ManyToManyField(to='announcements.category'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='clients',
            field=models.ManyToManyField(to='announcements.client'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='trainer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='announcements.trainer'),
        ),
    ]
