# Generated by Django 4.1.7 on 2023-04-12 17:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('announcements', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='calendar',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='announcement',
            name='categories',
            field=models.ManyToManyField(blank=True, to='announcements.category'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='clients',
            field=models.ManyToManyField(blank=True, related_name='announcement_client', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='announcement',
            name='trainer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcement_trainer', to=settings.AUTH_USER_MODEL),
        ),
    ]
