# Generated by Django 4.1.7 on 2023-04-24 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='types',
            field=models.CharField(choices=[('difficulty', 'Difficulty'), ('objectives', 'Objectives'), ('recovery', 'Recovery'), ('age', 'Age')], default='difficulty', max_length=20),
        ),
    ]
