# Generated by Django 4.1.7 on 2023-03-07 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0004_announcement_google_calendar_event_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='finish_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de fin'),
        ),
    ]
