# Generated by Django 4.1.7 on 2023-03-10 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('announcements', '0005_alter_announcement_finish_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainer',
            name='user',
        ),
        migrations.AlterField(
            model_name='announcement',
            name='categories',
            field=models.ManyToManyField(blank=True, to='announcements.category'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='clients',
            field=models.ManyToManyField(blank=True, to='users.client'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='trainer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.trainer'),
        ),
        migrations.DeleteModel(
            name='Client',
        ),
        migrations.DeleteModel(
            name='Trainer',
        ),
    ]
