# Generated by Django 4.1.7 on 2023-03-12 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0006_remove_trainer_user_alter_announcement_categories_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='types',
            field=models.CharField(choices=[('difficulty', 'Difficulty'), ('objectives', 'Objectives'), ('recovery', 'Recovery')], default='difficulty', max_length=20),
        ),
    ]
