# Generated by Django 4.1.7 on 2023-03-10 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0006_remove_trainer_user_alter_announcement_categories_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='finish_date',
            field=models.DateTimeField(verbose_name='Fecha de fin'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='start_date',
            field=models.DateTimeField(verbose_name='Fecha de inicio'),
        ),
    ]
