# Generated by Django 4.1.7 on 2023-03-13 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0003_alter_category_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='types',
            field=models.CharField(choices=[('difficulty', 'Difficulty'), ('objectives', 'Objectives'), ('recovery', 'Recovery')], default='difficulty', max_length=20),
        ),
    ]
