# Generated by Django 4.1.1 on 2023-03-06 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anuncios', '0003_alter_category_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='google_calendar_event_id',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='announcement',
            name='invitation_sent',
            field=models.BooleanField(default=False),
        ),
    ]
