# Generated by Django 4.1.7 on 2023-03-06 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anuncios', '0003_alter_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='clients',
            field=models.ManyToManyField(blank=True, to='anuncios.client'),
        ),
    ]
