# Generated by Django 4.1.7 on 2023-03-06 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anuncios', '0004_alter_announcement_clients'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='categories',
            field=models.ManyToManyField(blank=True, to='anuncios.category'),
        ),
    ]
