# Generated by Django 4.1.7 on 2023-03-11 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anuncios', '0005_alter_announcement_finish_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='categories',
            field=models.ManyToManyField(blank=True, to='anuncios.category'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='clients',
            field=models.ManyToManyField(blank=True, to='anuncios.client'),
        ),
    ]
