# Generated by Django 4.1.7 on 2023-03-12 09:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anuncios', '0007_announcement_difficulty_alter_announcement_capacity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='difficulty',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
